config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios do
    put :sort, on: :collection
  end

  get 'angular-items', to: 'portfolios#angular'

  get 'about-me', to: 'pages#about'

  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  include Placeholder

  has_many :technologies
  accepts_nested_attributes_for :technologies, reject_if: lambda { |attrs| attrs['name'].blank? }

  validates_presence_of :title, :body, :main_image, :thumb_image

  # two differnt ways to create custom scopes
  def self.angular
    where(subtitle: 'Angular')
  end

  scope :ruby_on_rails_portfolio_items, -> { where(subtitle: 'Ruby on Rails') }
  scope :angular_portfolio_items, -> { where(subtitle: 'Angular') }

  after_initialize :set_defaults

  def set_defaults
    self.main_image ||= Placeholder.image_generator(height: "600", width: "400")
    self.thumb_image ||= Placeholder.image_generator(height: "350", width: "200")
  end

  def self.by_position
    order("position ASC")
  end

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  layout "portfolio"
  access all: [:show, :index, :angular], user: {except: [:sort, :destroy, :new, :create, :update, :edit]}, site_admin: :all

  def index
    @portfolio_items = Portfolio.by_position
  end

  def sort
    #byebug
    params[:order].inspect
    params[:order].each do |key, value|
      Portfolio.find(key.to_i).update(position: value[:position].to_i)
    end
    render nothing: true
  end

  def angular
    @portfolio_angular_items = Portfolio.angular_portfolio_items
  end

  def new
    @portfolio_item = Portfolio.new
    3.times { @portfolio_item.technologies.build }
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html {redirect_to portfolios_path, notice: 'Your portfolio item is now live.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    @portfolio_item = Portfolio.find(params[:id])
  end

  def update
    @portfolio_item = Portfolio.find(params[:id])

    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html {redirect_to portfolios_path, notice: 'The record was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show
    @portfolio_item = Portfolio.find(params[:id])
  end

  def destroy
    @portfolio_item = Portfolio.find(params[:id])
    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio item was removed.' }
    end
  end

  private

  def portfolio_params
    params.require(:portfolio).permit(:title, :subtitle, :body,
      technologies_attributes: [:name])
  end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.haml
= form_for(portfolio_item) do |f|
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :subtitle
    = f.text_field :subtitle
  .field
    = f.label :body
    = f.text_area :body
  %ul
    = f.fields_for :technologies do |techf|
      %li
        = techf.label :name
        = techf.text_field :name
  .actions
    = f.submit

app/views/portfolios/_portfolio_item.html.haml
.col-md-4
  .card{data_id: portfolio_item.id}
    .mb-4.shadow-sm
      - unless portfolio_item.thumb_image.nil?
        %img.card-img-top{:src => portfolio_item.thumb_image}
      .card-body
        %p.card-text= portfolio_item.title
        -# %p.card-text= portfolio_item.body
        .d-flex.justify-content-between.align-items-center
          .btn-group
            %button.btn.btn-sm.btn-outline-secondary{:type => "button"} View
            %button.btn.btn-sm.btn-outline-secondary{:type => "button"} Edit
          %small.text-muted 9 mins



-# %p= link_to portfolio_item.title, portfolio_path(portfolio_item)
-# = image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil?
-# = link_to "Edit", edit_portfolio_path(portfolio_item) if logged_in?(:site_admin)
-# = link_to "Delete", portfolio_item, method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin)

app/views/portfolios/angular.html.haml
%h1 Angular Portfolio Items
= link_to "Create New Item", new_portfolio_url if logged_in?(:site_admin)
- @portfolio_angular_items.each do |p|
  %p= link_to p.title, portfolio_path(p)
  %p= p.subtitle
  %p= p.body
  = image_tag p.thumb_image unless p.thumb_image.nil?
  = link_to "Edit", edit_portfolio_path(p) if logged_in?(:site_admin)
  = link_to "Delete", p, method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin)

app/views/portfolios/edit.html.haml
%h1 Edit Portfolio Item
= render 'form', portfolio_item: @portfolio_item

app/views/portfolios/index.html.haml
%h1 Portfolio Items


.album.py-5.bg-light
  = link_to "Create New Item", new_portfolio_url if logged_in?(:site_admin)
  .container
    - sortclass = logged_in?(:site_admin) ? "sortable" : ""
    .row{class: sortclass} 
      = render partial: "portfolio_item", collection: @portfolio_items

app/views/portfolios/new.html.haml
%h1 Create a new Portfolio Item
= render 'form', portfolio_item: @portfolio_item

app/views/portfolios/new0.html.erb
<h1>Create a new Portfolio Item</h1>

<%= form_for(@portfolio_item) do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/portfolios/show.html.haml
= image_tag @portfolio_item.main_image
%h1= @portfolio_item.title
%em= @portfolio_item.subtitle
%p= @portfolio_item.body
%h2 Technologies Used:
- @portfolio_item.technologies.each do |t|
  %p= t.name